# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "/WAI" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"
  - "vendor"
  - "scripts"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-aria-practices

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: tsmd/wai-website-theme@tsmd

collections:

defaults:
  -
    scope:
      path: ""
    values:
      layout: "standalone_resource"
      standalone_resource_header:
        title: "ARIA Authoring Practices Guide (APG)"
        title-ref: /aria/apg/
        subtitle: "How to build accessibility semantics into web patterns and widgets"
      standalone_resource_nav_links:
        - name: APG Home
          ref: /ARIA/apg/
        - name: Patterns
          ref: /ARIA/apg/patterns/
        - name: Practices
          ref: /ARIA/apg/practices/
        - name: Index
          ref: /ARIA/apg/example-index/
        - name: About
          ref: /ARIA/apg/about/
#  -
#    scope:
#      path: "_business-case"
#    values:
#      layout: "sidenav"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - wai-website-plugin
